#!/bin/bash
set -euf -o pipefail
mkdir -p /home/nao/ros1_dependencies_sources/build/libccd
export PATH=$PATH:/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies/bin
cd /home/nao/ros1_dependencies_sources/build/libccd
../../src/libccd/bootstrap
../../src/libccd/configure \
  --prefix=/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies \
  --host=i686-aldebaran-linux-gnu \
  --build=x86_64-linux \
  --enable-shared
make -j8 install
