#!/bin/bash
set -euf -o pipefail
mkdir -p /home/nao/ros1_dependencies_sources/build/fcl
cd /home/nao/ros1_dependencies_sources/build/fcl
cmake \
  -DCMAKE_INSTALL_PREFIX=/home/nao/${PEPPER_INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_TOOLCHAIN_FILE=/home/nao/pepper_ros1_ws/ctc-cmake-toolchain.cmake \
  -DALDE_CTC_CROSS=/home/nao/ctc \
  ../../src/fcl
make -j8 install
